# Generated by Django 3.2.23 on 2024-01-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoappnew', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='2002-04-23'),
            preserve_default=False,
        ),
    ]
